version: "3"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - restaurant_network
    ports:
      - '5434:5432'
    volumes:
      - ./_modules/postgres/docker-entrypoint-initdb.sql:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sql

  restaurant:
    command: python3 app/__main__.py
    restart: always
    ports:
      - '8000:8000'
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: ${PYTHONPATH}:/code/app
    depends_on:
      - postgres
    networks:
      - restaurant_network

networks:
  restaurant_network: