name: CI-pipeline to build and push application's image

on:
  push:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_NAME: ${{ steps.extract_repository_name.outputs.repository_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Repository Name
        id: extract_repository_name
        run: echo "::set-output name=repository_name::$(echo "${{ github.repository }}" | cut -d'/' -f2)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
