name: CI-pipeline to build and push application's image

on:
  push:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Repository Name
        id: repository-selector
        run: echo "REPOSITORY_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          REPOSITORY_NAME: ${{ steps.repository-selector.outputs.REPOSITORY_NAME }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v3
        env:
          REPOSITORY_NAME: ${{ steps.repository-selector.outputs.REPOSITORY_NAME }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
