name: Release-drafter for quickview-streaming project

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        publish: true
        prerelease: false
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.OAUTH_TOKEN }}
